services:
  migrate:
    build: .
    image: computer-store-app
    command: ["node", "dist/db/setup.js"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy

  backend:
    build: .
    image: computer-store-app
    ports:
      - "3000:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  database:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 3s
      retries: 15

    volumes:
      - computer-store-db:/var/lib/postgresql

volumes:
  computer-store-db:
