// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { ErrorCheckData, ErrorCheckErrors, HealthCheckResponses, LoginData, LoginErrors, LoginResponses, LogoutErrors, LogoutResponses, MeErrors, MeResponses, RegisterData, RegisterErrors, RegisterResponses } from './types.gen.js';

export type RouteHandlers = {
    login: RouteHandler<{
        Body: LoginData['body'];
        Reply: LoginErrors & LoginResponses;
    }>;
    logout: RouteHandler<{
        Reply: LogoutErrors & LogoutResponses;
    }>;
    me: RouteHandler<{
        Reply: MeErrors & MeResponses;
    }>;
    register: RouteHandler<{
        Body: RegisterData['body'];
        Reply: RegisterErrors & RegisterResponses;
    }>;
    errorCheck: RouteHandler<{
        Params: ErrorCheckData['path'];
        Reply: ErrorCheckErrors;
    }>;
    healthCheck: RouteHandler<{
        Reply: HealthCheckResponses;
    }>;
};
