// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { AuthLogoutErrors, AuthLogoutResponses, AuthMeErrors, AuthMeResponses, AuthRegisterData, AuthRegisterErrors, AuthRegisterResponses, ErrorCheckData, ErrorCheckErrors, HealthCheckResponses, LoginData, LoginErrors, LoginResponses } from './types.gen.js';

export type RouteHandlers = {
    login: RouteHandler<{
        Body: LoginData['body'];
        Reply: LoginErrors & LoginResponses;
    }>;
    authLogout: RouteHandler<{
        Reply: AuthLogoutErrors & AuthLogoutResponses;
    }>;
    authMe: RouteHandler<{
        Reply: AuthMeErrors & AuthMeResponses;
    }>;
    authRegister: RouteHandler<{
        Body: AuthRegisterData['body'];
        Reply: AuthRegisterErrors & AuthRegisterResponses;
    }>;
    errorCheck: RouteHandler<{
        Params: ErrorCheckData['path'];
        Reply: ErrorCheckErrors;
    }>;
    healthCheck: RouteHandler<{
        Reply: HealthCheckResponses;
    }>;
};
