// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://example.com' | (string & {});
};

export type Credentials = {
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Пароль пользователя
     */
    password: string;
};

export type ErrorBadRequestError = ErrorProblemDetails;

export type ErrorConflictError = ErrorProblemDetails;

export type ErrorForbiddenError = ErrorProblemDetails;

export type ErrorInternalServerError = ErrorProblemDetails;

export type ErrorNotFoundError = ErrorProblemDetails;

export type ErrorProblemDetails = {
    type?: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
};

export type ErrorUnauthorizedError = ErrorProblemDetails;

export type ErrorCheckResponse = {
    error: string;
};

export type UserDto = {
    /**
     * Идентификатор пользователя
     */
    id: string;
    /**
     * Email пользователя
     */
    email: string;
};

export type LoginData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorBadRequestError;
    /**
     * Access is unauthorized.
     */
    401: ErrorUnauthorizedError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * The request has succeeded.
     */
    200: UserDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * Access is unauthorized.
     */
    401: ErrorUnauthorizedError;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeErrors = {
    /**
     * Access is unauthorized.
     */
    401: ErrorUnauthorizedError;
};

export type AuthMeError = AuthMeErrors[keyof AuthMeErrors];

export type AuthMeResponses = {
    /**
     * The request has succeeded.
     */
    200: UserDto;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthRegisterData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorBadRequestError;
    /**
     * The request conflicts with the current state of the server.
     */
    409: ErrorConflictError;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: UserDto;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type ErrorCheckData = {
    body?: never;
    path: {
        statusCode: 400 | 401 | 403 | 404 | 409 | 500;
    };
    query?: never;
    url: '/error-check/{statusCode}';
};

export type ErrorCheckErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorCheckResponse;
    /**
     * Access is unauthorized.
     */
    401: ErrorCheckResponse;
    /**
     * Access is forbidden.
     */
    403: ErrorCheckResponse;
    /**
     * The server cannot find the requested resource.
     */
    404: ErrorCheckResponse;
    /**
     * The request conflicts with the current state of the server.
     */
    409: ErrorCheckResponse;
    /**
     * Server error
     */
    500: ErrorCheckResponse;
};

export type ErrorCheckError = ErrorCheckErrors[keyof ErrorCheckErrors];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health-check';
};

export type HealthCheckResponses = {
    /**
     * The request has succeeded.
     */
    200: {
        status: 'ok';
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
